function KineticEnergy = autogen_kinetic_energy(I_bot,I_mid,I_top,dtheta_1,dtheta_2,dtheta_3,dx,dy,l_mid,l_top,m_bot,m_mid,m_motor1,m_motor2,m_top,r_com_mid,r_com_bot,r_com_top,theta_1,theta_2,theta_3)
%AUTOGEN_KINETIC_ENERGY
%    KINETICENERGY = AUTOGEN_KINETIC_ENERGY(I_BOT,I_MID,I_TOP,DTHETA_1,DTHETA_2,DTHETA_3,DX,DY,L_MID,L_TOP,M_BOT,M_MID,M_MOTOR1,M_MOTOR2,M_TOP,R_COM_MID,R_COM_BOT,R_COM_TOP,THETA_1,THETA_2,THETA_3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    01-Jun-2020 14:01:26

t2 = cos(theta_1);
t3 = sin(theta_1);
t4 = theta_1+theta_2;
t5 = dtheta_1.^2;
t6 = dtheta_2.^2;
t7 = l_top.*t2;
t8 = cos(t4);
t9 = l_top.*t3;
t10 = sin(t4);
t11 = t4+theta_3;
t12 = cos(t11);
t13 = sin(t11);
t14 = l_mid.*t8;
t15 = l_mid.*t10;
t16 = r_com_bot.*t13;
t17 = r_com_bot.*t12;
KineticEnergy = (I_top.*t5)./2.0+(I_bot.*(t5+t6+dtheta_3.^2))./2.0+(m_top.*((dx+dtheta_1.*r_com_top.*t2).^2+(dy+dtheta_1.*r_com_top.*t3).^2))./2.0+((dx+dtheta_1.*(t7+r_com_mid.*t8)+dtheta_2.*r_com_mid.*t8).^2+(dy+dtheta_1.*(t9+r_com_mid.*t10)+dtheta_2.*r_com_mid.*t10).^2).*(m_mid./2.0+m_motor1./2.0+m_motor2./2.0)+(I_mid.*(t5+t6))./2.0+(m_bot.*((dx+dtheta_2.*(t14+t17)+dtheta_3.*t17+dtheta_1.*(t7+t14+t17)).^2+(dy+dtheta_2.*(t15+t16)+dtheta_3.*t16+dtheta_1.*(t9+t15+t16)).^2))./2.0;
