function C_all = autogen_constraints(x,y)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jun-2020 20:56:38

C_all = [x;y];
