%% coriolis_matrix_uneven.m

function G = grav_vector_uneven(x,params)

theta_1 = x(3);
theta_2 = x(4);
theta_3 = x(5);

G = autogen_grav_vector(params.model.dyn.g,...
                        params.model.geom.mid.l,...
                        params.model.geom.top.l,...
                        params.model.dyn.bot.m,...
                        params.model.dyn.mid.m,...
                        params.model.dyn.motor1.m,...
                        params.model.dyn.motor2.m,...
                        params.model.dyn.top.m,...
                        params.model.dyn.mid.r_com,...
                        params.model.dyn.bot.r_com,...
                        params.model.dyn.top.r_com,...
                        theta_1,...
                        theta_2,...
                        theta_3);

end