%% H_eom.m
%
% Description:
%   Wrapper function for autogen_H.m
%   Computes H(q,q_dot) for the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   H: a 5x1 set of terms.

function H = H_eom(x,params)

theta_1 = x(3);
theta_2 = x(4);
theta_3 = x(5);
dtheta_1 = x(8);
dtheta_2 = x(9);
dtheta_3 = x(10);

H = autogen_H_eom(dtheta_1, dtheta_2, dtheta_3, params.model.dyn.g, params.model.geom.mid.l,...
                  params.model.geom.top.l, params.model.dyn.bot.m, params.model.dyn.mid.m,...
                  params.model.dyn.motor1.m, params.model.dyn.motor2.m, params.model.dyn.top.m,...
                  params.model.dyn.mid.r_com, params.model.dyn.bot.r_com, params.model.dyn.top.r_com,...
                  theta_1, theta_2, theta_3);

end