function C_all = autogen_constraints(x,y)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Jun-2020 18:10:13

C_all = [x;y];
