function C_all = autogen_constraints(x,y)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Jun-2020 22:52:58

C_all = [x;y];
