function Total_E = autogen_total_energy(I_bot,I_mid,I_top,dtheta_1,dtheta_2,dtheta_3,dx,dy,g,l_mid,l_top,m_bot,m_mid,m_motor1,m_motor2,m_top,r_com_mid,r_com_bot,r_com_top,theta_1,theta_2,theta_3,y)
%AUTOGEN_TOTAL_ENERGY
%    TOTAL_E = AUTOGEN_TOTAL_ENERGY(I_BOT,I_MID,I_TOP,DTHETA_1,DTHETA_2,DTHETA_3,DX,DY,G,L_MID,L_TOP,M_BOT,M_MID,M_MOTOR1,M_MOTOR2,M_TOP,R_COM_MID,R_COM_BOT,R_COM_TOP,THETA_1,THETA_2,THETA_3,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Jun-2020 18:09:18

t2 = cos(theta_1);
t3 = sin(theta_1);
t4 = theta_1+theta_2;
t5 = dtheta_1.^2;
t6 = dtheta_2.^2;
t12 = -y;
t7 = l_top.*t2;
t8 = cos(t4);
t9 = l_top.*t3;
t10 = sin(t4);
t11 = t4+theta_3;
t13 = cos(t11);
t14 = sin(t11);
t15 = l_mid.*t8;
t16 = r_com_mid.*t8;
t17 = l_mid.*t10;
t18 = r_com_bot.*t14;
t19 = r_com_bot.*t13;
Total_E = (I_top.*t5)./2.0+((dx+dtheta_1.*(t7+t16)+dtheta_2.*t16).^2+(dy+dtheta_1.*(t9+r_com_mid.*t10)+dtheta_2.*r_com_mid.*t10).^2).*(m_mid./2.0+m_motor1./2.0+m_motor2./2.0)+(I_bot.*(t5+t6+dtheta_3.^2))./2.0+(m_top.*((dx+dtheta_1.*r_com_top.*t2).^2+(dy+dtheta_1.*r_com_top.*t3).^2))./2.0+(I_mid.*(t5+t6))./2.0+(m_bot.*((dx+dtheta_2.*(t15+t19)+dtheta_3.*t19+dtheta_1.*(t7+t15+t19)).^2+(dy+dtheta_2.*(t17+t18)+dtheta_3.*t18+dtheta_1.*(t9+t17+t18)).^2))./2.0-g.*(m_mid+m_motor1+m_motor2).*(t7+t12+t16)+g.*m_top.*(y-r_com_top.*t2)-g.*m_bot.*(t7+t12+t15+t19);
