function C_all = autogen_constraints(x,y)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-May-2020 15:42:31

C_all = [x;y];
