%% coriolis_matrix_uneven.m

function C = coriolis_matrix_uneven(x,params)

theta_1 = x(3);
theta_2 = x(4);
theta_3 = x(5);
dx = x(6);
dy = x(7);
dtheta_1 = x(8);
dtheta_2 = x(9);
dtheta_3 = x(10);

C = autogen_coriolis_matrix(params.model.dyn.b1,...
                            params.model.dyn.b2,...
                            params.model.dyn.b3,...
                            params.model.dyn.b4,...
                            params.model.dyn.b5,...
                            dtheta_1,...
                            dtheta_2,...
                            dtheta_3,...
                            dx,...
                            dy,...
                            params.model.geom.mid.l,...
                            params.model.geom.top.l,...
                            params.model.dyn.bot.m,...
                            params.model.dyn.mid.m,...
                            params.model.dyn.motor1.m,...
                            params.model.dyn.motor2.m,...
                            params.model.dyn.top.m,...
                            params.model.dyn.mid.r_com,...
                            params.model.dyn.bot.r_com,...
                            params.model.dyn.top.r_com,...
                            theta_1,...
                            theta_2,...
                            theta_3);

end