function G = autogen_grav_vector(g,l_mid,l_top,m_bot,m_mid,m_top,r_com_mid,r_com_bot,r_com_top,theta_1,theta_2,theta_3)
%AUTOGEN_GRAV_VECTOR
%    G = AUTOGEN_GRAV_VECTOR(G,L_MID,L_TOP,M_BOT,M_MID,M_TOP,R_COM_MID,R_COM_BOT,R_COM_TOP,THETA_1,THETA_2,THETA_3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-May-2020 11:26:56

t2 = cos(theta_1);
t3 = theta_1+theta_2;
t4 = cos(t3);
t5 = t3+theta_3;
t6 = cos(t5);
t7 = l_mid.*m_bot.*t4;
t8 = m_mid.*r_com_mid.*t4;
t9 = m_bot.*r_com_bot.*t6;
G = [g.*(t7+t8+t9+l_top.*m_bot.*t2+l_top.*m_mid.*t2+m_top.*r_com_top.*t2);g.*(t7+t8+t9);g.*t9];
