function C = autogen_coriolis_matrix(b1,b2,b3,dtheta_1,dtheta_2,dtheta_3,l_mid,l_top,m_bot,m_mid,r_com_mid,r_com_bot,theta_2,theta_3)
%AUTOGEN_CORIOLIS_MATRIX
%    C = AUTOGEN_CORIOLIS_MATRIX(B1,B2,B3,DTHETA_1,DTHETA_2,DTHETA_3,L_MID,L_TOP,M_BOT,M_MID,R_COM_MID,R_COM_BOT,THETA_2,THETA_3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    04-May-2020 15:21:24

t2 = sin(theta_2);
t3 = sin(theta_3);
t4 = theta_2+theta_3;
t5 = sin(t4);
t6 = dtheta_1.*l_mid.*l_top.*m_bot.*t2.*2.0;
t7 = dtheta_2.*l_mid.*l_top.*m_bot.*t2.*2.0;
t8 = dtheta_1.*l_mid.*m_bot.*r_com_bot.*t3.*2.0;
t9 = dtheta_2.*l_mid.*m_bot.*r_com_bot.*t3.*2.0;
t10 = dtheta_3.*l_mid.*m_bot.*r_com_bot.*t3.*2.0;
t11 = dtheta_1.*l_top.*m_mid.*r_com_mid.*t2.*2.0;
t12 = dtheta_2.*l_top.*m_mid.*r_com_mid.*t2.*2.0;
t13 = -t7;
t14 = -t8;
t15 = -t9;
t16 = -t10;
t17 = -t12;
t18 = dtheta_1.*l_top.*m_bot.*r_com_bot.*t5.*2.0;
t19 = dtheta_2.*l_top.*m_bot.*r_com_bot.*t5.*2.0;
t20 = dtheta_3.*l_top.*m_bot.*r_com_bot.*t5.*2.0;
t21 = -t18;
t22 = -t19;
t23 = -t20;
C = reshape([b1+t13+t16+t17+t22+t23,t6+t11+t16+t18,m_bot.*r_com_bot.*(dtheta_1.*l_mid.*t3+dtheta_2.*l_mid.*t3+dtheta_1.*l_top.*t5).*2.0,-t6-t11+t13+t16+t17+t21+t22+t23,b2+t16,t8+t9,t14+t15+t16+t21+t22+t23,t14+t15+t16,b3],[3,3]);
