function Energy = autogen_Energy(I_bot,I_mid,I_top,dtheta_1,dtheta_2,dtheta_3,dx_top,dy_top,g,l_mid,l_top,m_bot,m_mid,m_motor1,m_motor2,m_top,r_com_mid,r_com_bot,r_com_top,theta_1,theta_2,theta_3,y_top)
%AUTOGEN_ENERGY
%    ENERGY = AUTOGEN_ENERGY(I_BOT,I_MID,I_TOP,DTHETA_1,DTHETA_2,DTHETA_3,DX_TOP,DY_TOP,G,L_MID,L_TOP,M_BOT,M_MID,M_MOTOR1,M_MOTOR2,M_TOP,R_COM_MID,R_COM_BOT,R_COM_TOP,THETA_1,THETA_2,THETA_3,Y_TOP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-May-2020 21:15:12

t2 = cos(theta_1);
t3 = sin(theta_1);
t4 = theta_1+theta_2;
t10 = -y_top;
t5 = l_top.*t2;
t6 = cos(t4);
t7 = l_top.*t3;
t8 = sin(t4);
t9 = t4+theta_3;
t11 = cos(t9);
t12 = sin(t9);
t13 = l_mid.*t6;
t14 = r_com_mid.*t6;
t15 = l_mid.*t8;
t16 = r_com_bot.*t12;
t17 = r_com_bot.*t11;
Energy = (I_mid.*(dtheta_1+dtheta_2).^2)./2.0+(I_top.*dtheta_1.^2)./2.0+(I_bot.*(dtheta_1+dtheta_2+dtheta_3).^2)./2.0+((dx_top+dtheta_1.*(t5+t14)+dtheta_2.*t14).^2+(dy_top+dtheta_1.*(t7+r_com_mid.*t8)+dtheta_2.*r_com_mid.*t8).^2).*(m_mid./2.0+m_motor1./2.0+m_motor2./2.0)+(m_top.*((dx_top+dtheta_1.*r_com_top.*t2).^2+(dy_top+dtheta_1.*r_com_top.*t3).^2))./2.0+(m_bot.*((dx_top+dtheta_2.*(t13+t17)+dtheta_3.*t17+dtheta_1.*(t5+t13+t17)).^2+(dy_top+dtheta_2.*(t15+t16)+dtheta_3.*t16+dtheta_1.*(t7+t15+t16)).^2))./2.0-g.*(m_mid+m_motor1+m_motor2).*(t5+t10+t14)+g.*m_top.*(y_top-r_com_top.*t2)-g.*m_bot.*(t5+t10+t13+t17);
