function M = autogen_mass_matrix(I_bot,I_mid,I_top,l_mid,l_top,m_bot,m_mid,m_motor1,m_motor2,m_top,r_com_mid,r_com_bot,r_com_top,theta_1,theta_2,theta_3)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(I_BOT,I_MID,I_TOP,L_MID,L_TOP,M_BOT,M_MID,M_MOTOR1,M_MOTOR2,M_TOP,R_COM_MID,R_COM_BOT,R_COM_TOP,THETA_1,THETA_2,THETA_3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-May-2020 21:15:55

t2 = cos(theta_1);
t3 = cos(theta_2);
t4 = cos(theta_3);
t5 = sin(theta_1);
t6 = theta_1+theta_2;
t7 = theta_2+theta_3;
t8 = l_mid.^2;
t9 = l_top.^2;
t10 = r_com_mid.^2;
t11 = r_com_bot.^2;
t25 = m_mid./2.0;
t26 = m_motor1./2.0;
t27 = m_motor2./2.0;
t29 = m_bot+m_mid+m_motor1+m_motor2+m_top;
t12 = cos(t6);
t13 = cos(t7);
t14 = sin(t6);
t15 = t6+theta_3;
t16 = m_top.*r_com_top.*t2;
t18 = m_top.*r_com_top.*t5;
t20 = m_bot.*t8;
t21 = m_bot.*t11;
t22 = m_mid.*t10;
t23 = m_motor1.*t10;
t24 = m_motor2.*t10;
t28 = l_mid.*l_top.*m_bot.*t3;
t30 = l_mid.*m_bot.*r_com_bot.*t4;
t31 = l_top.*m_mid.*r_com_mid.*t3;
t32 = l_top.*m_motor1.*r_com_mid.*t3;
t33 = l_top.*m_motor2.*r_com_mid.*t3;
t47 = t25+t26+t27;
t17 = cos(t15);
t19 = sin(t15);
t34 = t30.*2.0;
t35 = l_mid.*m_bot.*t12;
t36 = m_mid.*r_com_mid.*t12;
t37 = m_motor1.*r_com_mid.*t12;
t38 = m_motor2.*r_com_mid.*t12;
t39 = l_mid.*m_bot.*t14;
t40 = m_mid.*r_com_mid.*t14;
t41 = m_motor1.*r_com_mid.*t14;
t42 = m_motor2.*r_com_mid.*t14;
t43 = l_top.*m_bot.*r_com_bot.*t13;
t46 = I_bot+t21+t30;
t44 = m_bot.*r_com_bot.*t17;
t45 = m_bot.*r_com_bot.*t19;
t48 = t43+t46;
t49 = I_bot+I_mid+t20+t21+t22+t23+t24+t28+t31+t32+t33+t34+t43;
M = reshape([t29,0.0,t16+t35+t36+t37+t38+t44+l_top.*m_bot.*t2+l_top.*m_mid.*t2+l_top.*m_motor1.*t2+l_top.*m_motor2.*t2,t35+t36+t37+t38+t44,t44,0.0,t29,t18+t39+t40+t41+t42+t45+l_top.*m_bot.*t5+l_top.*m_mid.*t5+l_top.*m_motor1.*t5+l_top.*m_motor2.*t5,t39+t40+t41+t42+t45,t45,t16+t47.*(l_top.*t2.*2.0+r_com_mid.*t12.*2.0)+m_bot.*(l_mid.*t12+l_top.*t2+r_com_bot.*t17),t18+t47.*(l_top.*t5.*2.0+r_com_mid.*t14.*2.0)+m_bot.*(l_mid.*t14+l_top.*t5+r_com_bot.*t19),I_top+t28+t31+t32+t33+t43+t49+m_bot.*t9+m_mid.*t9+m_motor1.*t9+m_motor2.*t9+m_top.*r_com_top.^2,t49,t48,(m_bot.*(l_mid.*t12.*2.0+r_com_bot.*t17.*2.0))./2.0+r_com_mid.*t12.*t47.*2.0,(m_bot.*(l_mid.*t14.*2.0+r_com_bot.*t19.*2.0))./2.0+r_com_mid.*t14.*t47.*2.0,t49,I_bot+I_mid+t20+t21+t22+t23+t24+t34,t46,t44,t45,t48,t46,I_bot+t21],[5,5]);
