%% fwk_kin.m

% Description:
% Computes the forward kinematics for points on the robot.
% Inputs:
%   q: robot configuration, q = [x_top;y_top;theta1;theta2;theta3];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   FK: a 2x6 matrix of (x,y) locations of three points on the robot. Row 1
%   is the x-coordinate, row 2 is the y-coordinate:
%   FK = [x_com_top, x_tip_top, x_com_mid, x_tip_mid, x_com_bot, x_tip_bot;
%         y_com_top, y_tip_top, y_com_mid, y_tip_mid, y_com_bot, y_tip_bot];

function [FK] = fwd_kin(q,params)
    x_top = q(1);
    y_top = q(2);
    theta_1 = q(3);
    theta_2 = q(4);
    theta_3 = q(5);

    FK = autogen_fwd_kin(params.model.geom.bot.l,...
                         params.model.geom.mid.l,...
                         params.model.geom.top.l,...
                         params.model.geom.mid.r_com,...
                         params.model.geom.bot.r_com,...
                         params.model.geom.top.r_com,...
                         theta_1,theta_2,theta_3,x_top,y_top);
end













