function G = autogen_grav_vector(g,l_mid,l_top,m_bot,m_mid,m_motor1,m_motor2,m_top,r_com_mid,r_com_bot,r_com_top,theta_1,theta_2,theta_3)
%AUTOGEN_GRAV_VECTOR
%    G = AUTOGEN_GRAV_VECTOR(G,L_MID,L_TOP,M_BOT,M_MID,M_MOTOR1,M_MOTOR2,M_TOP,R_COM_MID,R_COM_BOT,R_COM_TOP,THETA_1,THETA_2,THETA_3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-May-2020 14:34:58

t2 = sin(theta_1);
t3 = theta_1+theta_2;
t4 = l_top.*t2;
t5 = sin(t3);
t6 = t3+theta_3;
t7 = sin(t6);
G = [g.*((t4+r_com_mid.*t5).*(m_mid+m_motor1+m_motor2)+m_bot.*(t4+l_mid.*t5+r_com_bot.*t7)+m_top.*r_com_top.*t2);g.*(l_mid.*m_bot.*t5+m_bot.*r_com_bot.*t7+m_mid.*r_com_mid.*t5+m_motor1.*r_com_mid.*t5+m_motor2.*r_com_mid.*t5);g.*m_bot.*r_com_bot.*t7];
