function C = autogen_constraints(x,y)
%AUTOGEN_CONSTRAINTS
%    C = AUTOGEN_CONSTRAINTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-May-2020 14:29:01

C = [x;y];
